services:
  pricing-system:
    container_name: lazi-pricing
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file:
      - .env.local
    networks:
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pricing.rule=Host(`pricing.lazilabs.com`)"
      - "traefik.http.routers.pricing.entrypoints=websecure"
      - "traefik.http.routers.pricing.tls.certresolver=letsencrypt"
      - "traefik.http.services.pricing.loadbalancer.server.port=3000"
      - "traefik.docker.network=traefik-net"

networks:
  traefik-net:
    external: true
